### ISSUE TITLE
Wrong push_constant block name

### ISSUE THREAD

**Issue by MuGdxy** [KhronosGroup/SPIRV-Reflect#140]
when I write such compute shader, expecting to get the push_constant block name as "pushConstantName", but finally get "PushConstantType".
```glsl
#version 450

layout (local_size_x = 256) in;
layout (push_constant) uniform PushConstantType
{
    int a;
} pushConstantName;

void main()
{
}
...
```
As you can see, in the  yml file, the type name of the push_constant block is the same as the name of the block, so, I think there is something wrong with the reflection. 
```yml
%YAML 1.0
---
all_type_descriptions:
  - &td0
    id: 11
    op: 21
    type_name: 
    struct_member_name: "a"
    storage_class: 0 # UniformConstant
    type_flags: 0x00000004 # INT 
    decoration_flags: 0x00000000 # NONE
    traits:
      numeric:
        scalar: { width: 32, signedness: 1 }
        vector: { component_count: 0 }
        matrix: { column_count: 0, row_count: 0, stride: 0 }
      image: { dim: 0, depth: 0, arrayed: 0, ms: 0, sampled: 0, image_format: 0 } # dim=1D image_format=Unknown
      array: { dims_count: 0, dims: [], stride: 0 }
    member_count: 0
    members:
  - &td1
    id: 12
    op: 30
    type_name: "PushConstantType"
    struct_member_name: 
    storage_class: -1 # NOT APPLICABLE
    type_flags: 0x10080000 # STRUCT EXTERNAL_BLOCK 
    decoration_flags: 0x00000001 # BLOCK 
    traits:
      numeric:
        scalar: { width: 0, signedness: 0 }
        vector: { component_count: 0 }
        matrix: { column_count: 0, row_count: 0, stride: 0 }
      image: { dim: 0, depth: 0, arrayed: 0, ms: 0, sampled: 0, image_format: 0 } # dim=1D image_format=Unknown
      array: { dims_count: 0, dims: [], stride: 0 }
    member_count: 1
    members:
      - *td0
all_block_variables:
  - &bv0
    name: "a"
    offset: 0
    absolute_offset: 0
    size: 4
    padded_size: 16
    decorations: 0x00000000 # NONE
    numeric:
      scalar: { width: 32, signedness: 1 }
      vector: { component_count: 0 }
      matrix: { column_count: 0, row_count: 0, stride: 0 }
    array: { dims_count: 0, dims: [], stride: 0 }
    member_count: 0
    members:
    type_description: *td0
  - &bv1
    name: "PushConstantType"
    offset: 0
    absolute_offset: 0
    size: 16
    padded_size: 16
    decorations: 0x00000000 # NONE
    numeric:
      scalar: { width: 0, signedness: 0 }
      vector: { component_count: 0 }
      matrix: { column_count: 0, row_count: 0, stride: 0 }
    array: { dims_count: 0, dims: [], stride: 0 }
    member_count: 1
    members:
      - *bv0
    type_description: *td1
all_descriptor_bindings:
all_interface_variables:
module:
  generator: 13 # Google Shaderc over Glslang
  entry_point_name: "main"
  entry_point_id: 4
  source_language: 2 # GLSL
  source_language_version: 450
  spirv_execution_model: 5 # GLCompute
  shader_stage: 0x00000020 # CS
  descriptor_binding_count: 0
  descriptor_bindings:
  descriptor_set_count: 0
  descriptor_sets:
  input_variable_count: 0,
  input_variables:
  output_variable_count: 0,
  output_variables:
  push_constant_count: 1,
  push_constants:
    - *bv1 # "PushConstantType"
...

```
