### ISSUE TITLE
Empty push constant block name after 56d6806

### ISSUE THREAD

**Issue by vladislavbelov** [KhronosGroup/SPIRV-Reflect#215]
We ([0 A.D.](https://play0ad.com/)) use block names (including push constants) to restrict and validate input GLSL from mods. With one of Vulkan SDK updates we got an assertion because of an empty push constant block name.

I've done some testing and debugging and it seems that after 56d6806ad1b6a210c4f745804a072189ad25c537 `spirv-reflect` no longer outputs a push constant block name. Particularly that line affected the output: https://github.com/KhronosGroup/SPIRV-Reflect/commit/56d6806ad1b6a210c4f745804a072189ad25c537#diff-14a0e64d286556f1314ed193dce8ec519d4511a867fa0bf2e82f45a9d4a95a80R3470. On that assignment `p_push_constant->name` already contains a correct name but `p_node->name` contains an empty string.

I'm not sure was it intentional or not but I think it'd good to output the push constant block name if possible.

**Sample**:
```glsl
// glslc -g -x glsl --target-env=vulkan1.1 -std=450core -fshader-stage=compute -O test.glsl -o test.spv
#version 450
layout (push_constant) uniform Constants
{
	vec4 Color;
};
layout(set = 0, binding = 0, rgba8) uniform image2D Output;
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main()
{
	imageStore(Output, ivec2(gl_WorkGroupID.xy), Color);
}
```

**Before**:
```yaml
# spirv-reflect --y test.spv
# ...
  - &bv2
    name: "Constants"
    offset: 0
    absolute_offset: 0
    size: 16
    padded_size: 16
# ...
```

**After**:
```yaml
# spirv-reflect --y test.spv
# ...
  - &bv2
    name: ""
    offset: 0
    absolute_offset: 0
    size: 16
    padded_size: 16
# ...
```

**Comment by spencer-lunarg** [comment]
In GLSL if I go

```glsl
layout (push_constant) uniform Constants {
	vec4 color;
} pc;

void main() {
    vec4 x = vec4(pc.color.x);
}
```

vs not giving it a name

```glsl

layout (push_constant) uniform Constants {
	vec4 color;
};

void main() {
    vec4 x = vec4(color.x);
}
```

I get

```patch
OpName %10 "Constants"
OpMemberName %10 0 "color"
- OpName %12 "pc"
+ OpName %12 ""

%10 = OpTypeStruct %7
%12 = OpVariable %11 PushConstant
```

when you go `spirv-reflect -y -v 1` (more verbose) you will see

```
all_type_descriptions:
  - &td1
    struct_member_name: "Constants"

all_block_variables:
  - &bv1
    name: "pc"
```

Which seems to be as designed and don't think there is anything to do in `spirv-reflect`

----

While you can only have a single Push Constant struct in GLSL, but in theory a shading language could go

```
struct Constants {
    vec4 color;
};

layout (push_constant) uniform Constants pc;
layout (set = 0) uniform Constants something_else;
```

in this case `Constants` is not the variable name, but is just the type name
